### ISSUE TITLE
Sorting of pre-release versions is wrong

### ISSUE THREAD

**Issue by stof** [h4cc/hhvm-progress#55]
The package page is sorting versions in descending order, but pre-release versions are before the corresponding stable release while they should be after (they are lower versions)

![hhvm_progress_prerelease_version](https://cloud.githubusercontent.com/assets/439401/5960087/656e738e-a7d3-11e4-9d46-661255f25d3c.png)

**Comment by h4cc** [comment]
I honestly dont know how to sort such versions _always_ correctly. As far as i can see, even packagist simply orders by `releasedAt` instead of using versions for such:

https://github.com/composer/packagist/blob/cc2f686775c2e309cdc285632ee0cce596f87071/src/Packagist/WebBundle/Entity/VersionRepository.php#L86

My bad is now, that this timestamp `releasedAt` is currently not stored in the database.
For such a change a need to update the database entries from packagist. This is what i will try then.

**Comment by h4cc** [comment]
Found another way, simply using PHP's `version_compare()`:

http://php.net/manual/en/function.version-compare.php :four_leaf_clover:

**Comment by h4cc** [comment]
Fixed ist, looks far better now:
http://hhvm.h4cc.de/package/behat/behat

Thanks! :+1:
